version: '3.9'

services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    image: user/beauty
    depends_on:
      - db
    working_dir: /var/www/html/src
    entrypoint: '/usr/local/bin/php'
    # -d xdebug.mode=debug -d xdebug.start_with_request=yes -d xdebug.idekey=docker artisan serve --host 0.0.0.0
    #command: '-d xdebug.mode=debug artisan serve --host 0.0.0.0'
    volumes:
      - ./:/var/www/html/
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - host.docker.internal:host-gateway
