version: '3.9'

services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - database:/var/lib/mysql 
    ports:
      - "9906:3306"

  web:
    build: .
    image: user/beauty
    depends_on:
      - db
    working_dir: /var/www/html/src
    entrypoint: '/usr/local/bin/php'
    volumes:
      - ./:/var/www/html/
    command: '-d xdebug.mode=debug -d xdebug.start_with_request=yes artisan serve --host 0.0.0.0'
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    image: node:current-alpine3.17
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/
    command: 'npm run dev'
    ports:
      - "5173:5173"


volumes:
  database:
